stages:
  - test
  - build
  - deploy

unit-test-job:
  stage: test

  image: python:3.10-slim-buster # for pip and unit tests

  before_script:
    - apt-get update && apt-get install make # for make cmd
  script:
    - make test
  after_script:
    - echo "Unit tests complete."

build-job:
  stage: build
  variables:
    NAME: jwsharp/chess
    TAG: python-app-1.0

    DOCKER_TLS_CERTDIR: "/certs"

  # Connect client and server
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind

  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t $NAME:$TAG
    - docker push $NAME:$TAG
  after_script:
    - echo "Container successfully built."

deploy-job:
  stage: deploy

  environment: production # may change environment

  script:
    - 
  after_script:
    - echo "Application successfully deployed."