stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "build phase"

unit-test-job:
  stage: test
  image: python:3.10-slim-buster # for pip and unit tests
  before_script:
    - apt-get update && apt-get install make # for make cmd
  script:
    - make test
  after_script:
    - echo "Unit tests complete."

deploy-job:
  stage: deploy
  environment: production # may change environment
  script:
    - echo "deploy phase"
  after_script:
    - echo "Application successfully deployed."